### PR TITLE
Draft: added recipe151 and updated requirements.txt

### LINKED ISSUE #30: Recipe request: demonstrate features of Robot Framework Browser library
It would be helpful to have at least a basic recipe to demonstrate the features of Robot Framework Browser.

See here for more details:
https://github.com/MarketSquare/robotframework-browser

### PR DESCRIPTION
**Pull request by tuxmux28**
Fixes #30

### CODE REVIEW

**Comment by bhirsz** [comment]
I've took a quick look why the CI is failing. Looks like:
1) robotframework-browser package only supports python 3.7+. We need to decide if 
   a) we want to skip all tests on python 3.6
   b) somehow change our github action to not run browser tests (and dependency install..) on python 3.6
2) There are extra steps required to setup robotframework-browser: we need to install nodejs and run rfbrowser init command

Easiest would be just skipping browser test in current CI and maybe implementing it as seperate action? As we require special setup, we have special requirements (like python version) etc
@adrianyorke

**Comment by adrianyorke** [comment]
**we want to skip all tests on python 3.6**
There's a lot of 3.6 around still so we should check against this version for backwards compatibility.

**Easiest would be just skipping browser test in current CI and maybe implementing it as seperate action?**
Yes, whatever approach is easiest to implement.  This may not be the last custom build we need to get recipes passing.  A similar approach may be required for the SeleniumLib recipe for example.

I wrote this to Christop earlier in an IM - might help implement the node-js build:
In future, in order to run CI tests we would need to create a continuous integration (CI) workflow to build and test a Node.js project as described here:
https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs

**Comment by adrianyorke** [comment]
@tuxmux28 I've converted this PR to draft as I know you have a few more changes in mind.

@bhirsz has joined the party.  He is changing the CI so we can select which version(s) of Python we would like to build against using Force Tags concept.  He's also setting up a node.js build which we can use specifically for testing browser - watch this space!

**Comment by adrianyorke** [comment]
@tuxmux28 CI Testing has now been enhanced to split Python builds and also incorportate node.js.
You need to change the following:
Force Tags______no-ci-testing
to:
Force Tags______py3.7    py3.8
Note: do not use underscore (_) - I only used that to show the spacing.

**Comment by adrianyorke** [comment]
@tuxmux28 Let me know if you require assistance finishing this PR off.  Simply reverse your changes to tests/requirements.txt and replace the no-ci-testing tag and we are good to go.

Actually, we don't know if it's going to work as we don't have a browser script to test it but I'm sure we can deal with whatever arises.

**Pull request closed without merging**
