### PR TITLE
Add initial action workflow

### PR DESCRIPTION
**Pull request by bhirsz**
This PR add Github action workflow that runs recipe examples. The workflow is splitted in few steps: 

1. Checkout the code
2. Install dependencies (I gathered libraries from recipe documentation and put it into tests\requirements.txt file)
3. Run Robocop - Robot Framework linter - which will only fail on errors **(currently 3 errors are present)**
4. Run Robot recipe tests 
5. Run parallel Robot recipe test - the run command is different so I splitted it into seperate step

At this moment 25-26/32 tests are working. There are problems with SSH tests (we're missing ssh host we could connect to), AWS (missing env variables).

Under Windows database tests doesn't work (but they work on Ubuntu). The opposite happens with Selenium tests - probably because of invalid webdriver config (missing in PATH?). 

If you know how to fix some of issues right away feel free to commit to this PR. Otherwise I will investigate them.

### CODE REVIEW

**Comment by bhirsz** [comment]
Job view contain also artifacts: 
image

It should be artifact from the last run of the matrix - in our case Windows and Python 3.8. Should I create seperate artifact for each platform x python version? It would be probably usefull for debugging (if something breaks - like now we have tests working on one platform but not on the other). But we would overclutter github servers ;)

**Comment by adrianyorke** [comment]
Looking good.

It's probably more important that we run CI tests on a linux build rather than Windows as I guess that is what most people will be using?  Or did you have something else in mind here?

One idea, let's add a new robot script variable that indicates if the recipe is suitable for CI testing.  Both the SSH and AWS recipes have external dependencies that are configured by the tester before they run the script.  I would initially set ${CI_Testing} to a falsy value (e.g. False or No) for these recipes.  All other recipes would have a truthy value (e.g. True or Yes).  What do you think?

If you like this idea then ${CI_Testing} would become a new mandatory variable for each recipe.  I can update all existing recipes on this branch.

**Comment by bhirsz** [comment]
Actually I saw often that RF are executed on both environments - development is being done in Windows and CI/CD on some Unix host. That's why I would like to support both if its possible.

I think using tags to control if test should be executed or not is more in line with how Robot Framework is used. 

Robocop is independent so it will scan tests every time anyway

**Comment by adrianyorke** [comment]
Support for both Linux and Windows is great so please do if it's not too much trouble.

I also agree with your list of Python versions.  Many people are still using 3.6 or 3.7 and 3.8 is quite stable.  3.9 is probably too bleeding edge right now and is likely to be unstable for a while.

I would like to implement `nocitests `tags so we can merge this version.  I will add the `Force Tags` on the relevant recipes once I merge this PR and I have seen it failing on the SSH and AWS tests.  After my PR, it should no longer fail :-)

There are free, public SSH service so no mocking require for that recipe:
https://serverfault.com/questions/185153/free-public-ssh-server-for-testing-purposes
I guess we could SSH to the CI host also perhaps as a default?  For Windows, SSH is not enabled by default iirc.

Mocking AWS is tricky.  The RF AWS library is also trying to solve that problem.  Local Stack has been suggested but that is really heavy and has 400+ open issues which I don't have time to resolve.

**Comment by adrianyorke** [comment]
@bhirsz I added a commit which adds the Force Tag statements.  I also pushed a change to update the commit message using --force-with-lease option so it should not affect your work.  You will need to merge this commit to your local branch to be up to date before you can make further changes.

**Comment by adrianyorke** [comment]
I see __pycache__ directory - perhaps something like this in top-level .gitignore:

```
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
```

**Comment by adrianyorke** [comment]
How easy would it be to add a check against pep8/flake8 for Python scripts?  I see there are no class or function docstrings in this script for example:
`tests/robocop_rules.py`

**Comment by bhirsz** [comment]
"I would like to implement no-ci-tests processing so we can merge this version." 
I will update it tommorow/Monday to exclude tests with this tag

"Would we like to restrict this to only the recipe being added/amended in the future?" 
There is no need to limit test runs - for open source we have unlimited Github Action resources ;) And we don't use that much. So we can run them all. Of course it would be good idea to not use 'any' version in requirement but specific one (ie. robotframework-robocop==1.1.0) and then use something like dependabot to auto update our dependencies which would trigger CI run and inform us if new lib version break our tests or not.

Thanks for the URL for SSH server, I will take a look and try to implement it - but for now I will disable the test and raise seperate PR if I manage to get it working. And I will skip AWS as it's too bothersome to get working in CI/CD ;). 

"see pycache directory in tests/ directory "
My fault, I forgot to update .gitignore, I will do clean up before final review

"How easy would it be to add a check against pep8/flake8 for Python scripts? For example there are no class or method docstrings in this script:"
I will update this script - it was just `quick and dirty` script. But adding pep8/flake8 tests (we could try pylama as sort of integration of many python linter tools) is very easy so I will do it too.

**Comment by adrianyorke** [comment]
All robocop tests are now passing in all envs after this commit https://github.com/adrianyorke/robotframework-cookbook/pull/26/commits/35ae5a3fdb6420807e30e594f97237177aed906c

**Review by adrianyorke — APPROVED** [review]
Let's add Python linting in a new PR, this one is a big step forward.

**Pull request merged**
