### PR TITLE
add logo files

### PR DESCRIPTION
**Pull request by ericbjones**
adds official logo files for robot-cookbook

### CODE REVIEW

**Comment by ericbjones** [comment]
image

**Comment by ericbjones** [comment]
image

**Comment by ericbjones** [comment]
logo_black_transparent

logo_white_transparent

**Comment by ericbjones** [comment]
90E0E365-B80D-4C35-9FE0-2F7167FA1AB9

**Comment by ericbjones** [comment]
FA09D126-E044-4420-BCC2-A83E6BD3287E

**Comment by adrianyorke** [comment]
@all-contributors please add @ericbjones for Design

**Comment by adrianyorke** [comment]
We are getting some ECONRESET messages from CI but they don't seem to be caused by the content of cookbook so I will merge this.

**Pull request merged**
