### PR TITLE
fix #73 bumps min version to 3.8

### LINKED ISSUE #73: Time to bump Python versions - drop support for 3.7 and add 3.10
The CI workflows for this project currently support Python versions 3.7, 3.8 and 3.9.
Remove support for Python 3.7 and add support for Python 3.10.

### PR DESCRIPTION
**Pull request by kiblik1**
#73  Bump supported vesion in recipes.

### CODE REVIEW

**Comment by adrianyorke** [comment]
Thanks for the PR @kiblik1. You would also need to change line 16 in the main workflow file so the CI creates the correct matrix:
https://github.com/adrianyorke/robotframework-cookbook/blob/master/.github/workflows/main.yml

**Comment by kiblik1** [comment]
Forgot about that, it should be fixed now.

**Comment by kiblik1** [comment]
Enclosed versions in quotes moght work now

**Comment by adrianyorke** [comment]
Agreed, I found this - looks like the fix is to surround the version in quotes otherwise YAML treats as numeric and truncates the zero:
https://github.com/actions/setup-python/issues/160

**Comment by adrianyorke** [comment]
Looks like it needs "requirements-3.10.txt" file in the test folder. I guess it makes sense to start with a copy of 3.9. Let's see if that works.

**Comment by adrianyorke** [comment]
Merged - many thanks @kiblik1

**Comment by adrianyorke** [comment]
@all-contributors please add @kiblik1 for Code

**Pull request merged**
