### PR TITLE
chore: remove support for python 3.9

### LINKED ISSUE #102: Time to bump Python versions - drop support for 3.9
The CI workflows for this project currently support Python versions 3.9, 3.10 and 3.11.
Remove support for Python 3.9 and add support for Python 3.12.

### PR DESCRIPTION
**Pull request by ChinoUkaegbu**
Fixes #102

### CODE REVIEW

**Comment by adrianyorke** [comment]
Thanks for the PR @ChinoUkaegbu 👍

**Comment by adrianyorke** [comment]
Python 3.12 CI tests are failing, both ubuntu and windows. You could try changing webdrivermanager to webdriver_manager in requirements 3.12, as per this discussion:
https://github.com/MarketSquare/webdrivermanager/issues/103

**Comment by ChinoUkaegbu** [comment]
Done!

**Comment by adrianyorke** [comment]
Thanks @ChinoUkaegbu.

Unfortunately, webdrivermanager depends on versioneer which does not currently support Python 3.12.

In order get your PR merged, I suggest cookbook should only supports Python 3.10 and 3.11 at this time. We can revist adding support for Python 3.12 at a later date when versioneer has caught up.

More info:
https://github.com/python-versioneer/python-versioneer

**Comment by ChinoUkaegbu** [comment]
I see, I've reflected the changes so support for 3.9 is dropped.

**Comment by adrianyorke** [comment]
@all-contributors please add @ChinoUkaegbu for Code

**Review by adrianyorke — APPROVED** [review]

**Comment by adrianyorke** [comment]
Excellent work @ChinoUkaegbu, thank you 🙏

**Comment by ChinoUkaegbu** [comment]
You're welcome, glad I could help!

**Pull request merged**
