### PR TITLE
Added instructions on how to clone the repository to the readme

### PR DESCRIPTION
**Pull request by jepoy92**
This work was done for issue #77

### CODE REVIEW

**Comment by adrianyorke** [comment]
Thanks for this, looks good @jepoy92 

A few minor changes then I can merge:
1. spelling of "useage": should be "usage"
2. "pip install" is repeated on this line "pip install pip install robotframework"
3. add "$" to front of this command "pip install -r .\requirements-[version].txt"

You can add a new commit to your master branch and simply push again and this PR will be updated with your additional changes.

**Comment by adrianyorke** [comment]
Hi @jepoy92 I trust all is well. Would you be able to complete the final updates this week perhaps? We have some more updates for the README in the backlog so it would be good to get your changes merged so you can avoid conflicts with other work.

**Comment by adrianyorke** [comment]
Hi @jepoy92, If you are struggling for time I can merge the changes as they are and fix the minor changes. Let me know if you would prefer this approach. Your base update is close, only a few minor fixes are needed then we can merge.

**Comment by jepoy92** [comment]
Hey Adria, just saw this message now. I'll make the changes right now.

**Comment by jepoy92** [comment]
The changes have been pushed and are ready for your review

**Comment by adrianyorke** [comment]
Looks good and all checks are passing. I will merge this branch and add you to the contributors!

**Comment by adrianyorke** [comment]
@all-contributors please add @jepoy92 for documentation & maintenance

**Pull request merged**
