### PR TITLE
Added recipe for DateTime section

### PR DESCRIPTION
**Pull request by szabolcstoth**
The recipe contains two test cases to:
- log the elapsed time using result_format=verbose,
- log the passed days and years using result_format=datetime.

### CODE REVIEW

**Comment by adrianyorke** [comment]
Thanks for the pull request @szabolcstoth 

One minor issue:
`Invalid variable name '${{$days_passed_since_release.days / 365}'.`

I changed the last robot script line to the two lines below and it now returns "28.76164383561644 years passed!" which is about right:
    ${years_passed_since_release}=    Evaluate    $days_passed_since_release.days / 365
    Log    ${years_passed_since_release} years passed!

**Comment by szabolcstoth** [comment]
Hello! Thanks for the reply. I successfully executed the Robot code before I created the pull request (check the attached log.html).
The inline Python evaluation works from Robot Framework 3.2.0, that is why I highlighted in the documentation that I used that feature. Which version of Robot Framework are you using?
[recipe031_handling_dates.zip](https://github.com/adrianyorke/robotframework-cookbook/files/4842894/recipe031_handling_dates.zip)
If you propose to aim for the compatibility, I can use `Evaluate` for sure. Should I update my code?

**Comment by adrianyorke** [comment]
You can also use extended variable syntax using a single line:

`Log    ${days_passed_since_release.days / 365} years passed!`

**Comment by adrianyorke** [comment]
Yes, you are right - this machine has version 3.1.2.

Maybe the extended variable syntax is that way to go as it is also backwards compatible?

**Comment by adrianyorke** [comment]
This is your recipe so the decision is yours :-)  I am happy with all 3 versions but the original may fail more often.  If you go with the original code, then mention it is only compatible with robot framework version 3.2 and later.

**Comment by szabolcstoth** [comment]
I replaced inline Python evaluation to extended variable syntax. ;)

**Comment by adrianyorke** [comment]
Merged.  Thank you @szabolcstoth, nice recipe to help robot beginners get started.

**Pull request merged**
