### PR TITLE
added first browser recipe

### PR DESCRIPTION
**Pull request by tuxmux28**

### CODE REVIEW

**Comment by bhirsz** [comment]
Tests are working on Windows but not on Ubuntu. You probably need "xvfb" installed - after figuring out what we need to get Browser working on Linux it will be good to mention this in doc

**Comment by adrianyorke** [comment]
@bhirsz - some comments from Slack messaging:

I was looking over on Browser project - they have steps like this in their CI:
https://github.com/MarketSquare/robotframework-browser/actions/runs/291578746/workflow
    - name: Start xvfb
      run: |
        export DISPLAY=:99.0
        Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 &
    - name: Run Robot Framework tests
      run: |
        xvfb-run --auto-servernum inv atest

**Comment by adrianyorke** [comment]
The Windows tests are working nicely - here are the screenshots:
https://files.slack.com/files-pri/T07PJQ9S7-F01BY60CY2K/robotframework-browser-screenshot-1.png
https://files.slack.com/files-pri/T07PJQ9S7-F01CCTSD0LA/robotframework-browser-screenshot-2.png
https://files.slack.com/files-pri/T07PJQ9S7-F01CK3433RS/robotframework-browser-screenshot-3.png

**Comment by adrianyorke** [comment]
OP is quite busy with work commitments - if anyone wishes to work on the PR before it is merged, the following commands can be used to 
`git fetch origin pull/38/head:feature/browser`
`git checkout feature/browser`
(you don't have to call your local branch feature/browser but it might be helpful if you wish to push)

I will try this out in Ubuntu and POP_OS to see if I can get it working locally.

**Comment by adrianyorke** [comment]
Ok, I got this working on Pop!_OS quite easily.  I didn't change the recipe in this pull request so this is purely a CI configuration issue.  Here are the steps I followed on a clean istall of Pop!_OS:
$ sudo apt install python3-pip
$ pip3 install robotframework
added robot to path using ~/.bashrc
$ pip3 install robotframework-browser
$ pip3 install --upgrade protobuf
$ sudo apt install nodejs
$ sudo apt-get install npm
$ rfbrowser init
$ robot recipe151_working_with_browser_contexts.robot

**Comment by adrianyorke** [comment]
Perhaps we only run these test on Windows initially?  Then we can merge this recipe and CI will be working.  Next, we can look at getting xvfb started - this is clearly a requirement of browser so it should be stated in the recipe for anyone trying to get this recipe working on a linux platform.

**Comment by mkorpela** [comment]
I debugged the current test case a bit. Mainly because I think that the test should be able to run without a headful browser and suite setup and teardown could be removed. Browser library will manage browser creation and destruction automatically.

It seems that the first test case "Context with no Geolocation Permission" runs into permission problems.
This seems to block everything in headless mode. It actually gets stuck to Click and for some reason does not survive from there onward.

**Comment by adrianyorke** [comment]
Check Slack Browser channel - there are some suggestions.  We should definitely add `Wait Until Network Is Idle` keyword before the `Take Screenshot` keywords so we can be sure that the browser has actually finished loading the map.  Also, typo in one comment: Sedney -> Sydney

**Comment by mkorpela** [comment]
Also added a bug report about system getting stuck when headless and would require a permission https://github.com/MarketSquare/robotframework-browser/issues/416

**Comment by mkorpela** [comment]
And really nice tests you have here :)

**Comment by adrianyorke** [comment]
@tuxmux28 : just confirming that adding `Wait Until Network Is Idle` keyword has fixed the blank screenshot issue on my Pop_OS VM.

**Comment by tuxmux28** [comment]
> 
> 
> And really nice tests you have here :)

Thanks :) if I think about it, they are not real tests. RPA might be more suitable.

**Review by adrianyorke — APPROVED** [review]
There seems to be some challenges with the CI but I don't see any specific problems with this recipe.  Let's merge and keep an eye on the CI.

**Comment by adrianyorke** [comment]
Merged, thanks @tuxmux28 for the recipe and thanks for helping us improve the CI to support different versions of Python & nodejs.

**Pull request merged**
