### PR TITLE
Split Continuous Integration tests based on Python versions

### PR DESCRIPTION
**Pull request by bhirsz**
Allow to define what python version are supported inside recipe (with py{version} tags)
Add nodejs and rfbrowser init setup for robotframework-browser support

### CODE REVIEW

**Review by adrianyorke — CHANGES_REQUESTED** [review]
Check column alignment of Force Tags in the following recipes:
src/section_03/recipe031_handling_dates.robot
src/section_07/recipe071_string_manipulation_examples.robot

**Review by adrianyorke — CHANGES_REQUESTED** [review]
Any reason for leading space in python-version (main.yml)?  Other list type literals don't seem to have this but I accept it doesn't change the functionality.
python-version: [ 3.6, 3.7, 3.8]

**Comment by adrianyorke** [comment]
Thanks, looks great.  Two minor observations.  Fix those and I will merge.

**Comment by bhirsz** [comment]
> Any reason for leading space in python-version (main.yml)? Other list type literals don't seem to have this but I accept it doesn't change the functionality.
> python-version: [ 3.6, 3.7, 3.8]

No reason, I will remove it

**Comment by bhirsz** [comment]
> @bhirsz: Thanks, looks great. Two minor observations. Fix those and I will merge.
> 
> Another topic, what are you thoughts on Python 3.9? I notice several projects have added this recently. We could also consider dropping 3.6 although I do like having an older version for backwards compatibility testing.

3.6 is still very popular (at least in corporate companies I worked with, where it was often default python). I would stick to it if there is not too much effort. At least we don't support Python 2 :D 
We can add 3.9 in separate PR (or even this one) - it should be compatible

**Comment by adrianyorke** [comment]
I noticed this in main.yml - not quite sure how it works:
`--include pabotANDpy${{ matrix.python-version }}`
So for py 3.6 it resolves to tag `--include pabotANDpy3.6` but I don't see that tag in the relevant script?

**Comment by bhirsz** [comment]
> I noticed this in main.yml - not quite sure how it works:
> `--include pabotANDpy${{ matrix.python-version }}`
> So for py 3.6 it resolves to tag `--include pabotANDpy3.6` but I don't see that tag in the relevant script?

This is how Robot Framework tags works - AND and OR are special reserved words. It's described here https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#tag-patterns
In this case it will match both pabot and py3.6 tags. If I would include them separetly ie `--include pabot --include py3.6` it would be the same effect as `--include pabotORpy3.6`

**Comment by bhirsz** [comment]
Looks like Python 3.9 don't work out of the box - I will revert last commit and add 3.9 support in separate PR

**Comment by adrianyorke** [comment]
> Looks like Python 3.9 don't work out of the box - I will revert last commit and add 3.9 support in separate PR

Thanks for trying.  A little too "bleading edge" by the looks of it.

**Comment by adrianyorke** [comment]
> > I noticed this in main.yml - not quite sure how it works:
> > `--include pabotANDpy${{ matrix.python-version }}`
> > So for py 3.6 it resolves to tag `--include pabotANDpy3.6` but I don't see that tag in the relevant script?
> 
> This is how Robot Framework tags works - AND and OR are special reserved words. It's described here https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#tag-patterns
> In this case it will match both pabot and py3.6 tags. If I would include them separetly ie `--include pabot --include py3.6` it would be the same effect as `--include pabotORpy3.6`

Excellent,  I didn't know about this but it makes perfect sense as it definitely would switch to OR if you list them separately.

**Pull request merged**
